name: Build Catwoman Mod
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Build Mod
      run: dotnet build --configuration Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Catwoman-Mod-DLL
        path: bin/Release/**/*.dll
